# Generated by Django 5.0.6 on 2026-06-06 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_orderitem_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='review_comment',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='review_created_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='review_rating',
        ),
    ]
